import {
  getEventTickets,
  searchEventTickets,
} from '../src/controllers/event-ticket.controller';
import { EventTicketService } from '../src/services/event-ticket.service';
import { encodePaginationCursor } from '../src/utils/pagination-cursor';

jest.mock('../src/services/event-ticket.service', () => ({
  EventTicketService: {
    getEventTickets: jest.fn(),
    searchEventTickets: jest.fn(),
  },
}));

describe('event-ticket controller search', () => {
  const eventTicketService = EventTicketService as unknown as {
    getEventTickets: jest.Mock;
    searchEventTickets: jest.Mock;
  };

  const createResponse = () => {
    const res = {
      status: jest.fn().mockReturnThis(),
      json: jest.fn().mockReturnThis(),
    };
    return res;
  };

  beforeEach(() => {
    jest.clearAllMocks();
    jest.spyOn(console, 'error').mockImplementation(() => {});
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  describe('getEventTickets', () => {
    it('passes a decoded cursor to the service when present', async () => {
      const cursor = encodePaginationCursor(
        new Date('2026-07-01T12:00:00.000Z'),
        '507f191e810c19729de860ea',
      );
      const req = {
        query: {
          cursor,
          limit: '8',
        },
      };
      const res = createResponse();

      const serviceResult = {
        page: 1,
        limit: 8,
        total: 2,
        nextCursor: null,
        tickets: [],
      };

      eventTicketService.getEventTickets.mockResolvedValue(serviceResult);

      await getEventTickets(req as any, res as any, jest.fn());

      expect(eventTicketService.getEventTickets).toHaveBeenCalledWith(
        1,
        8,
        {
          sortValue: new Date('2026-07-01T12:00:00.000Z'),
          id: '507f191e810c19729de860ea',
        },
      );
      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.json).toHaveBeenCalledWith(serviceResult);
    });

    it('returns 400 for invalid cursor payloads', async () => {
      const req = {
        query: {
          cursor: 'not-a-valid-cursor',
        },
      };
      const res = createResponse();

      await getEventTickets(req as any, res as any, jest.fn());

      expect(res.status).toHaveBeenCalledWith(400);
      expect(res.json).toHaveBeenCalledWith({
        error: 'Invalid cursor',
        message:
          'Cursor must be a valid pagination cursor generated by the API',
      });
    });
  });

  it('returns 400 when both search query and filters are missing', async () => {
    const req = {
      query: {},
    };
    const res = createResponse();

    await searchEventTickets(req as any, res as any, jest.fn());
    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json).toHaveBeenCalledWith({
      error: 'Invalid query',
      message:
        'At least one search parameter is required (q or filters like location/date/privacy)',
    });
  });

  it('returns 400 for invalid page number', async () => {
    const req = {
      query: {
        q: 'hackathon',
        page: '-1',
      },
    };
    const res = createResponse();

    await searchEventTickets(req as any, res as any, jest.fn());

    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json).toHaveBeenCalledWith({
      error: 'Invalid page number',
      message: 'Page number must be greater than 0',
    });
  });

  it('calls service and returns 200 for valid search request', async () => {
    const req = {
      query: {
        q: 'web3',
        page: '1',
        limit: '5',
      },
    };
    const res = createResponse();

    const serviceResult = {
      page: 1,
      limit: 5,
      total: 1,
      tickets: [
        {
          title: 'Web3 Builders Meetup',
          status: 'Wallet-Required',
          participantsCount: 50,
          anonymityPercentage: '60%',
          date: 'Oct 15, 2026',
          time: '6 PM',
          timezone: '(UTC +01:00)',
          location: 'Lagos',
          price: 0,
          imageUrl: 'https://example.com/image.jpg',
        },
      ],
    };

    eventTicketService.searchEventTickets.mockResolvedValue(serviceResult);

    await searchEventTickets(req as any, res as any, jest.fn());

    expect(eventTicketService.searchEventTickets).toHaveBeenCalledWith(
      'web3',
      1,
      5,
      {},
    );
    expect(res.status).toHaveBeenCalledWith(200);
    expect(res.json).toHaveBeenCalledWith(serviceResult);
  });

  it('supports filter-based discovery without q', async () => {
    const req = {
      query: {
        location: 'Lagos',
        privacyLevel: '1',
        paymentPrivacy: '0',
        eventType: '0',
        isPublished: 'true',
        startDate: '2026-04-01T00:00:00.000Z',
        endDate: '2026-04-30T23:59:59.000Z',
      },
    };
    const res = createResponse();

    const serviceResult = {
      page: 1,
      limit: 8,
      total: 0,
      tickets: [],
    };

    eventTicketService.searchEventTickets.mockResolvedValue(serviceResult);

    await searchEventTickets(req as any, res as any, jest.fn());

    expect(eventTicketService.searchEventTickets).toHaveBeenCalledWith(
      '',
      1,
      8,
      {
        location: 'Lagos',
        privacyLevel: 1,
        paymentPrivacy: 0,
        eventType: 0,
        isPublished: true,
        startDate: new Date('2026-04-01T00:00:00.000Z'),
        endDate: new Date('2026-04-30T23:59:59.000Z'),
      },
    );
    expect(res.status).toHaveBeenCalledWith(200);
    expect(res.json).toHaveBeenCalledWith(serviceResult);
  });

  it('calls next(error) when service throws an unexpected error', async () => {
    const req = {
      query: { q: 'error' },
    };
    const res = createResponse();
    const next = jest.fn();

    eventTicketService.searchEventTickets.mockRejectedValue(
      new Error('service failure'),
    );

    await searchEventTickets(req as any, res as any, next);

    expect(next).toHaveBeenCalledWith(expect.any(Error));
    expect(res.status).not.toHaveBeenCalled();
  });
});
