name: CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Execute project build
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    name: Execute lint check
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint:check

  tests:
    runs-on: ubuntu-latest
    name: Execute project tests
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  result:
    runs-on: ubuntu-latest
    name: Generate result
    if: always()
    needs:
      - build
      - lint
      - tests
    steps:
      - name: Generate result
        run: |
          get_mark() {
            if [ "$1" = "success" ]; then echo "✅"; else echo "❌"; fi
          }
          
          echo "Build result: $(get_mark '${{ needs.build.result }}')"
          echo "Lint result: $(get_mark '${{ needs.lint.result }}')"
          echo "Tests result: $(get_mark '${{ needs.tests.result }}')"
          
          if [ "${{ needs.build.result }}" != "success" ] || [ "${{ needs.tests.result }}" != "success" ]; then
            exit 1
          fi